server:
  port: 8080

spring:
  application:
    name: hawk-service
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/hawk
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    ai.codehawk: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

github:
  webhook:
    secret: "your_github_webhook_secret"